framework:
    messenger:
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    login: 'rabbitmq'
                    password: 'rabbitmq'
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
            async_priority_high:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    login: 'rabbitmq'
                    password: 'rabbitmq'
                    exchange:
                        name: 'high_priority'
                retry_strategy:
                    max_retries: 3
                    delay: 5000
                    multiplier: 1
            async_priority_low:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    login: 'rabbitmq'
                    password: 'rabbitmq'
                    exchange:
                        name: 'low_priority'
                retry_strategy:
                    max_retries: 3
                    delay: 5000
                    multiplier: 1
            failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'

        default_bus: messenger.bus.default

        buses:
            messenger.bus.default: []

        routing:
            Symfony\Component\Mailer\Messenger\SendEmailMessage: async
            App\Message\HighPriorityMessage: async_priority_high
            App\Message\LowPriorityMessage: async_priority_low
